services:
    kodify_blog.serializer.normalizer.object:
        class: Kodify\BlogBundle\Normalizer\Normalizer
        public: false
        parent: serializer.normalizer.object
        tags:
            - { name: serializer.normalizer }
