const Constants = {
  POSTS_FETCHING: 'POST_FETCHING',
  POSTS_RECEIVED: 'POSTS_RECEIVED',
  POST_FETCHING: 'POST_FETCHING',
  POST_RECEIVED: 'POST_RECEIVED',
  POST_SAVING: 'POST_SAVING',
  POST_SAVED: 'POST_SAVED',
  AUTHOR_SAVING: 'AUTHOR_SAVING',
  AUTHOR_SAVED: 'AUTHOR_SAVED',
  AUTHORS_FETCHING: 'AUTHORS_FETCHING',
  AUTHORS_RECEIVED: 'AUTHORS_RECEIVED',
};

export default Constants;
