<?php

namespace Kodify\BlogBundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends AbstractBaseRepository
{
    const LIST_DEFAULT_LIMIT = 8;
}
